generate_initial_pma:
  description: >
    Generate comprehensive pest management advice (PMA) for the queried pest scenario
    using {{problem_statement}}.
  expected_output: >
    A complete pest management advice document in markdown format.
  agent: editor

make_customisation_plan:
  description: >
    Review the initial PMA and identify knowledge gaps in the pest management decision.
    Recommend trustworthy sources and search queries to address them.
  expected_output: >
    A JSON object listing identified gaps, suggested queries, and recommended sources.
  agent: retriever

knowledge_retrieval:
  description: >
    Retrieve and summarise detailed information from recommended online sources
    to fill the knowledge gaps identified in the customisation plan.
  expected_output: >
    A structured report summarising retrieved information and how it fills each identified gap.
  agent: retriever

generate_customised_pma:
  description: >
    Integrate retrieved information with the initial PMA to create a customised,
    final pest management advice document.
  expected_output: >
    A final customised pest management advice document in markdown format.
  agent: editor

validate_threshold:
  description: >
    Verify that the customised PMA's threshold decision aligns with
    diagnostic data and authoritative guidelines. Make corrections if necessary.
  expected_output: >
    A validated PMA with confirmed or corrected pest management decision and supporting rationale.
  agent: validator
